name: 'Build docker image'
description: 'Build and load or push a tagged docker image for stump'

inputs:
  username:
    description: 'Username for docker login'
    required: true
  password:
    description: 'Token for docker login'
    required: true
  load:
    description: 'Set output-type to docker'
    default: 'true'
  push:
    description: 'Set output-type to registry'
    default: 'false'
  tags:
    description: 'List of tags to assigned to the image'
    default: 'nightly'
  platforms:
    description: 'List of platforms to build'
    required: true
  discord-webhook:
    description: 'Discord webhook to send notifications to'
    required: true

runs:
  using: composite
  steps:
    - name: Get commit short sha
      run: echo "GIT_REV=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      shell: bash

    - name: Format tags
      run: |
        echo "TAGS=$(echo ${{ inputs.tags }} | sed -e 's/,/,aaronleopold\/stump:/g' | sed -e 's/^/aaronleopold\/stump:/')" >> $GITHUB_ENV
      shell: bash

    - name: Setup rust
      uses: ./.github/actions/setup-rust
      with:
        # Note: until some sort of local caching is implemented, we don't want to cache dependencies
        # because the network overhead is too high and eats up lots of time
        cache-dependencies: ${{ runner.environment != 'self-hosted' }}

    # We only need QEMU when an arm* platform is targeted
    - name: Check QEMU requirement
      id: check-qemu
      run: |
        if [[ ${{ inputs.platforms }} == *"arm"* ]]; then
          echo "SETUP_QEMU=1" >> $GITHUB_OUTPUT
        else
          echo "SETUP_QEMU=0" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      if: ${{ steps.check-qemu.outputs.SETUP_QEMU == '1' }}
      with:
        platforms: linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      # if both inputs are empty, we assume we're running on a fork and don't need to login
      if: ${{ inputs.username != '' && inputs.password != '' }}
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Install podman
      if: runner.environment != 'self-hosted'
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
      shell: bash

    - name: Run podman buildx
      run: |
        ENGINE=podman PLATFORMS="${{ inputs.platforms }}" TAGS="${{ env.TAGS }}" GIT_REV="${{ env.GIT_REV }}" ./docker/build.sh
      shell: bash

    - name: Discord notification
      if: ${{ success() && inputs.push == 'true' && inputs.discord-webhook != '' }}
      env:
        DISCORD_WEBHOOK: ${{ inputs.discord-webhook }}
      uses: 'Ilshidur/action-discord@0.3.2'
      with:
        args: 'Successfully pushed the following image tags to registry: ${{ env.TAGS }}'
