name: 'Build Stump server'
description: 'Compile the Stump Rust server'

inputs:
  platform:
    description: 'The plaform of the runner'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Setup rust
      uses: ./.github/actions/setup-rust

    - name: Copy bundled web app
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ./apps/server/dist

    - name: Compile server
      shell: bash
      run: cargo build --package stump_server --release
