name: Build Stump server
description: Compile the Stump Rust server

runs:
  using: composite
  steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Setup rust
      uses: ./.github/actions/setup-rust

    # This action can be called to build in a Linux, macOS, or Windows runner
    # This step only runs when using Linux
    - name: Compile server (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: cargo build --package stump_server --release
    - name: Compile server (macOS)
      # Alternatively, when running macOS
      if: runner.os == 'macOS'
      shell: bash
      run: cargo build --package stump_server --release
    - name: Compile server (Windows)
      # Alternatively, when running Windows
      if: runner.os == 'Windows'
      shell: powershell
      run: cargo build --package stump_server --release
