import { ReadiumLocator } from '@stump/graphql'
import { format, formatISO, sub } from 'date-fns'

const now = new Date()
// readthrough 1
const rt1s1Start = sub(now, { months: 9, hours: 4, minutes: 30 })
const rt1s1End = sub(now, { months: 9, hours: 3, minutes: 52 })
const rt1s2Start = sub(now, { months: 9, days: -7, hours: 4 })
const rt1s2End = sub(now, { months: 9, days: -7, hours: 2, minutes: 30 })
const rt1Completed = sub(now, { months: 8, hours: 2, minutes: 45 })

// readthrough 2
const rt2s1Start = sub(now, { weeks: 2, hours: 2 })
const rt2s1End = sub(now, { weeks: 2, minutes: 30 })

export const fakeData = {
	totalElapsedSeconds: 70200, // ~19.5 hours
	// readthroughs newest-first, sessions newest-first within each, events newest-first within each session
	// so need to make sure i do that in backend if i keep a lot of this ui around
	readthroughs: [
		{
			readthroughNumber: 2,
			startedAt: formatISO(rt2s1Start),
			finishedAt: null,
			status: 'READING',
			totalElapsedSeconds: 5400, // 1.5 hours
			sessions: [
				{
					session: {
						__typename: 'ReadingSession' as const,
						id: 3,
						mediaId: 'mediaId',
						userId: 'oromeiId',
						readthroughNumber: 2,
						sessionDate: format(rt2s1Start, 'yyyy-MM-dd'),
						status: 'READING',
						startPage: 1,
						endPage: 62,
						startPercentage: '0.00',
						endPercentage: '0.094',
						elapsedSeconds: 5400,
						deviceIds: [],
						startLocator: {
							__typename: 'ReadiumLocator' as const,
							chapterTitle: 'A Long-Expected Party',
							href: 'chapter-001.xhtml',
							title: null,
							type: 'application/xhtml+xml',
							locations: null,
							text: null,
						} as ReadiumLocator,
						endLocator: {
							__typename: 'ReadiumLocator' as const,
							chapterTitle: 'A Conspiracy Unmasked',
							href: 'chapter-005.xhtml',
							title: null,
							type: 'application/xhtml+xml',
							locations: null,
							text: null,
						},
						notes: null,
						koreaderProgress: null,
						createdAt: formatISO(rt2s1Start),
						updatedAt: formatISO(rt2s1End),
					},
					events: [
						{
							__typename: 'Bookmark' as const,
							id: 'bookmark-006',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							page: 61,
							previewContent: 'Some preview of this page content would be nice here',
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'A Conspiracy Unmasked',
								href: 'chapter-005.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: null,
							} as ReadiumLocator,
							createdAt: formatISO(sub(rt2s1Start, { minutes: -88 })),
						},
						{
							__typename: 'MediaAnnotation' as const,
							id: 'annotation-005',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							annotationText: 'really thoughtful and honest note here from me',
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'A Long-Expected Party',
								href: 'chapter-001.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: {
									__typename: 'ReadiumText' as const,
									highlight: 'All that is gold does not glitter',
									before: null,
									after: null,
								},
							},
							createdAt: formatISO(sub(rt2s1Start, { minutes: -65 })),
							updatedAt: formatISO(sub(rt2s1Start, { minutes: -65 })),
						},
						{
							__typename: 'Bookmark' as const,
							id: 'bookmark-004',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							page: 55,
							previewContent: 'Some preview of this page content would be nice here',
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'Three is Company',
								href: 'chapter-003.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: null,
							},
							createdAt: formatISO(sub(rt2s1Start, { minutes: -20 })),
						},
					],
				},
			],
		},
		{
			readthroughNumber: 1,
			startedAt: formatISO(rt1s1Start),
			finishedAt: formatISO(rt1Completed),
			status: 'FINISHED',
			totalElapsedSeconds: 64800, // ~18 hours
			sessions: [
				{
					session: {
						__typename: 'ReadingSession' as const,
						id: 2,
						mediaId: 'mediaId',
						userId: 'oromeiId',
						readthroughNumber: 1,
						sessionDate: format(rt1s2Start, 'yyyy-MM-dd'),
						status: 'READING',
						startPage: 47,
						endPage: 198,
						startPercentage: '0.071',
						endPercentage: '0.299',
						elapsedSeconds: 5400, // 90 min
						deviceIds: [],
						startLocator: null,
						endLocator: {
							__typename: 'ReadiumLocator' as const,
							chapterTitle: 'The Council of Elrond',
							href: 'chapter-014.xhtml',
							title: null,
							type: 'application/xhtml+xml',
							locations: null,
							text: null,
						},
						notes: null,
						koreaderProgress: null,
						createdAt: formatISO(rt1s2Start),
						updatedAt: formatISO(rt1s2End),
					},
					events: [
						{
							__typename: 'Bookmark' as const,
							id: 'bookmark-005',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							page: 183,
							previewContent: null,
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'Many Meetings',
								href: 'chapter-013.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: null,
							},
							createdAt: formatISO(sub(rt1s2Start, { minutes: -87 })),
						},
						{
							__typename: 'MediaAnnotation' as const,
							id: 'annotation-004',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							annotationText: 'really thoughtful and honest note here from me',
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'The Council of Elrond',
								href: 'chapter-014.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: {
									__typename: 'ReadiumText' as const,
									highlight: 'Some really important quote from the book idk',
									before: null,
									after: null,
								},
							},
							createdAt: formatISO(sub(rt1s2Start, { minutes: -82 })),
							updatedAt: formatISO(sub(rt1s2Start, { minutes: -79 })),
						},
						{
							__typename: 'MediaAnnotation' as const,
							id: 'annotation-003',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							annotationText: null,
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'A Knife in the Dark',
								href: 'chapter-011.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: {
									__typename: 'ReadiumText' as const,
									highlight: 'Not all those who wander are lost',
									before: null,
									after: null,
								},
							},
							createdAt: formatISO(sub(rt1s2Start, { minutes: -70 })),
							updatedAt: formatISO(sub(rt1s2Start, { minutes: -70 })),
						},
						{
							__typename: 'Bookmark' as const,
							id: 'bookmark-003',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							page: 127,
							previewContent: 'Some preview of this page content would be nice here',
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'A Knife in the Dark',
								href: 'chapter-011.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: null,
							},
							createdAt: formatISO(sub(rt1s2Start, { minutes: -52 })),
						},
					],
				},
				{
					session: {
						__typename: 'ReadingSession' as const,
						id: 1,
						mediaId: 'mediaId',
						userId: 'oromeiId',
						readthroughNumber: 1,
						sessionDate: format(rt1s1Start, 'yyyy-MM-dd'),
						status: 'READING',
						startPage: 1,
						endPage: 47,
						startPercentage: '0.00',
						endPercentage: '0.071',
						elapsedSeconds: 2280, // 38 min
						deviceIds: [],
						startLocator: null,
						endLocator: {
							__typename: 'ReadiumLocator' as const,
							chapterTitle: 'Three is Company',
							href: 'chapter-003.xhtml',
							title: null,
							type: 'application/xhtml+xml',
							locations: null,
							text: null,
						},
						notes: null,
						koreaderProgress: null,
						createdAt: formatISO(rt1s1Start),
						updatedAt: formatISO(rt1s1End),
					},
					events: [
						{
							__typename: 'MediaAnnotation' as const,
							id: 'annotation-002',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							annotationText: 'really thoughtful and honest note here from me',
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'The Shadow of the Past',
								href: 'chapter-002.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: {
									__typename: 'ReadiumText' as const,
									highlight: 'Some really important quote from the book idk',
									before: null,
									after: null,
								},
							},
							createdAt: formatISO(sub(rt1s1Start, { minutes: -28 })),
							updatedAt: formatISO(sub(rt1s1Start, { minutes: -28 })),
						},
						{
							__typename: 'Bookmark' as const,
							id: 'bookmark-002',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							page: 32,
							previewContent: 'Some preview of this page content would be nice here',
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'The Shadow of the Past',
								href: 'chapter-002.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: null,
							},
							createdAt: formatISO(sub(rt1s1Start, { minutes: -29 })),
						},
						{
							__typename: 'MediaAnnotation' as const,
							id: 'annotation-001',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							annotationText: null,
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'A Long-Expected Party',
								href: 'chapter-001.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: {
									__typename: 'ReadiumText' as const,
									highlight: 'Some really important quote from the book idk',
									before: null,
									after: null,
								},
							},
							createdAt: formatISO(sub(rt1s1Start, { minutes: -22 })),
							updatedAt: formatISO(sub(rt1s1Start, { minutes: -22 })),
						},
						{
							__typename: 'Bookmark' as const,
							id: 'bookmark-001',
							mediaId: 'mediaId',
							userId: 'oromeiId',
							page: 1,
							previewContent: 'Some preview of this page content would be nice here',
							locator: {
								__typename: 'ReadiumLocator' as const,
								chapterTitle: 'A Long-Expected Party',
								href: 'chapter-001.xhtml',
								title: null,
								type: 'application/xhtml+xml',
								locations: null,
								text: null,
							},
							createdAt: formatISO(sub(rt1s1Start, { minutes: -15 })),
						},
					],
				},
			],
		},
	],
}

// mocking out reading timeline data will be a bit annoying, and maintaining a static list like this
// will be more annoying. im thinking maybe a script in tests/ that generates a bunch of data? idk
// it also isn't that deep
