/* eslint-disable @typescript-eslint/ban-types */
// DO NOT MODIFY THIS FILE, IT IS AUTOGENERATED

export type StumpVersion = { semver: string; rev: string | null; compile_time: string }

export type LoginOrRegisterArgs = { username: string; password: string }

export type ClaimResponse = { is_claimed: boolean }

export type MediaMetadataOverview = {
	genres: string[]
	writers: string[]
	pencillers: string[]
	inkers: string[]
	colorists: string[]
	letterers: string[]
	editors: string[]
	publishers: string[]
	characters: string[]
	teams: string[]
}
