name: Setup system dependencies
description: Install system dependencies and setup cache

inputs:
  cache-dependencies:
    description: 'Cache dependencies. This does not affect the Prisma client cache.'
    required: false
    default: 'true'

  cache-locality:
    description: 'The locality of the cache, e.g. either local build or docker build'
    required: false
    default: 'local' # 'local' or 'docker'

  additional-targets:
    description: 'Additional targets to install'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.81.0
        profile: minimal
        override: true
        components: rustfmt, clippy
        target: ${{ inputs.additional-targets }}

    - name: Configure environment
      if: ${{ runner.environment != 'self-hosted' && runner.os != 'Windows' }}
      shell: bash
      run: CHECK_NODE=0 CHECK_CARGO=0 DEV_SETUP=0 ./scripts/system-setup.sh

    # See https://github.com/Swatinem/rust-cache/issues/194
    - name: Cache Rust Dependencies
      if: ${{ inputs.cache-dependencies == 'true' }}
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: stump-rust-cache

    - name: Restore cached Prisma client
      id: cache-prisma-restore
      uses: actions/cache/restore@v3
      with:
        path: core/src/prisma.rs
        key: ${{ runner.os }}-prisma-${{ hashFiles('**/schema.prisma') }}-${{ inputs.cache-locality }}

    - name: Generate Prisma client
      if: ${{ steps.cache-prisma-restore.outputs.cache-hit != 'true' }}
      shell: bash
      run: cargo prisma generate --schema=./core/prisma/schema.prisma

    - name: Save Prisma client
      id: cache-prisma-save
      if: ${{ steps.cache-prisma-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: core/src/prisma.rs
        key: ${{ runner.os }}-prisma-${{ hashFiles('**/schema.prisma') }}-${{ inputs.cache-locality }}
