name: Setup system dependencies
description: Install system dependencies and setup cache

runs:
  using: composite
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.79.0
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Configure environment
      if: ${{ runner.name != 'oromei-ubuntu' && runner.os != 'Windows' }}
      shell: bash
      run: CHECK_NODE=0 CHECK_CARGO=0 DEV_SETUP=0 ./scripts/system-setup.sh

    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: stump-rust-cache

    - name: Restore cached Prisma client
      id: cache-prisma-restore
      uses: actions/cache/restore@v3
      with:
        path: core/src/prisma.rs
        key: ${{ runner.os }}-prisma-${{ hashFiles('**/schema.prisma') }}

    - name: Generate Prisma client
      if: ${{ steps.cache-prisma-restore.outputs.cache-hit != 'true' }}
      shell: bash
      run: cargo prisma generate --schema=./core/prisma/schema.prisma

    - name: Save Prisma client
      id: cache-prisma-save
      if: ${{ steps.cache-prisma-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v3
      with:
        path: core/src/prisma.rs
        key: ${{ runner.os }}-prisma-${{ hashFiles('**/schema.prisma') }}
        restore-keys: ${{ runner.os }}-prisma-${{ hashFiles('**/schema.prisma') }}
