name: 'Setup stump'
description: 'Install dependencies to buld stump'

inputs:
  platform:
    description: 'Runner platform'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy
    - uses: pnpm/action-setup@v2.0.1
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - name: install dependencies (ubuntu only)
      if: inputs.platform == 'ubuntu-20.04'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
