//! The sync token is an string that is used to track the client's progress through the
//! sync. It is generated by the server and opaque to the client, so we can use it to
//! store any necessary information we need.
//
//! It is generated by the server and sent to the client in a /v1/library/sync response,
//! in the "x-kobo-synctoken" header.
//
//! The client passes the value back to the server in its next /v1/library/sync request,
//! in the "x-kobo-synctoken" header.
use axum::http::HeaderValue;
use base64::{engine::general_purpose::STANDARD_NO_PAD as BASE64, Engine};
use std::str::Utf8Error;

use reqwest::header::{InvalidHeaderValue, ToStrError};
use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SyncToken {
	/// a token indicating that there are more pages to retrieve in this sync session.
	/// "V1" in the type leaves room for us to modify this format.
	IncompleteV1 {
		/// the ID of the database KoboSyncSession
		sync_id: String,

		/// the offset of the next page that should be sent to the client.
		next_offset: usize,
	},
	// a token indicating that this is the final page of this sync session.
	CompletedV1 {
		/// the ID of the database KoboSyncSession
		sync_id: String,
	},
	// once we're proxying to the kobo store we'll add a third type of sync token that will
	// indicate that we're done internal pagination and are paginating through the upstream sync.
}

#[derive(Error, Debug)]
pub enum SyncTokenSerializeError {
	#[error("Could not serialize JSON: {0}")]
	JSONError(#[from] serde_json::Error),
	#[error("Could not encode this token as a header: {0}")]
	InvalidHeaderError(#[from] InvalidHeaderValue),
}

#[allow(clippy::enum_variant_names)]
#[derive(Error, Debug)]
pub enum SyncTokenDeserializeError {
	#[error("Could not deserialize string from header: {0}")]
	HeaderToStrError(#[from] ToStrError),
	#[error("Could not decode UTF-8: {0}")]
	UTF8Error(#[from] Utf8Error),
	#[error("Could not decode Base64: {0}")]
	Base64Error(#[from] base64::DecodeError),
	#[error("Could not deserialize JSON: {0}")]
	JSONError(#[from] serde_json::Error),
}

impl SyncToken {
	pub fn new(sync_id: String, completed: bool, next_offset: usize) -> Self {
		if completed {
			SyncToken::CompletedV1 { sync_id }
		} else {
			SyncToken::IncompleteV1 {
				sync_id,
				next_offset,
			}
		}
	}

	fn try_from_base64_str(s: &str) -> Result<Self, SyncTokenDeserializeError> {
		let json_bytes = BASE64.decode(s)?;
		let json = std::str::from_utf8(&json_bytes)?;
		serde_json::from_str(json).map_err(Into::into)
	}

	pub fn try_from_header_value(
		hv: &HeaderValue,
	) -> Result<Self, SyncTokenDeserializeError> {
		let s = hv.to_str()?;
		Self::try_from_base64_str(s)
	}

	fn try_to_base64_string(self) -> Result<String, SyncTokenSerializeError> {
		let json = serde_json::to_string(&self)?;
		Ok(BASE64.encode(json))
	}

	pub fn try_to_header_value(self) -> Result<HeaderValue, SyncTokenSerializeError> {
		let s = self.try_to_base64_string()?;
		HeaderValue::from_str(s.as_ref()).map_err(Into::into)
	}
}
