coverage:
  status:
    project:
      default:
        target: 10%
    patch:
      default:
        target: 0%
ignore:
  - 'crates/cli'
  - 'crates/codegen'
  - 'crates/prisma-cli'
  - 'apps/desktop'
