version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: monthly
      time: '03:00'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    versioning-strategy: increase
    target-branch: 'nightly'

  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '04:00'
    labels:
      - 'dependencies'
    target-branch: 'nightly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
      time: '05:00'
    labels:
      - 'dependencies'
    target-branch: 'nightly'
