// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct LibraryToTag {
	pub rowid: i32,
	pub A: String,
	pub B: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct LibraryToUser {
	pub rowid: i32,
	pub A: String,
	pub B: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct MediaToTag {
	pub rowid: i32,
	pub A: String,
	pub B: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct SeriesToTag {
	pub rowid: i32,
	pub A: String,
	pub B: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct PrismaMigration {
	pub id: String,
	pub checksum: String,
	pub finished_at: Option<NaiveDateTime>,
	pub migration_name: String,
	pub logs: Option<String>,
	pub rolled_back_at: Option<NaiveDateTime>,
	pub started_at: NaiveDateTime,
	pub applied_steps_count: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct AgeRestriction {
	pub rowid: i32,
	pub age: i32,
	pub restrict_on_unset: bool,
	pub user_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct ApiKey {
	pub id: i32,
	pub name: String,
	pub short_token: String,
	pub long_token_hash: String,
	pub permissions: Vec<u8>,
	pub created_at: NaiveDateTime,
	pub last_used_at: Option<NaiveDateTime>,
	pub expires_at: Option<NaiveDateTime>,
	pub user_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct BookClubBookSuggestionLike {
	pub rowid: i32,
	pub timestamp: NaiveDateTime,
	pub liked_by_id: String,
	pub suggestion_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BookClubBookSuggestion {
	pub id: String,
	pub title: Option<String>,
	pub author: Option<String>,
	pub url: Option<String>,
	pub notes: Option<String>,
	pub suggested_by_id: String,
	pub book_id: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BookClubBook {
	pub id: String,
	pub start_at: NaiveDateTime,
	pub end_at: NaiveDateTime,
	pub discussion_duration_days: Option<i32>,
	pub title: Option<String>,
	pub author: Option<String>,
	pub url: Option<String>,
	pub book_entity_id: Option<String>,
	pub book_club_schedule_book_club_id: Option<String>,
	pub image_url: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BookClubDiscussionMessageLike {
	pub id: String,
	pub timestamp: NaiveDateTime,
	pub liked_by_id: String,
	pub message_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BookClubDiscussionMessage {
	pub id: String,
	pub content: String,
	pub timestamp: NaiveDateTime,
	pub is_top_message: bool,
	pub deleted_at: Option<NaiveDateTime>,
	pub parent_message_id: Option<String>,
	pub discussion_id: String,
	pub member_id: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BookClubDiscussion {
	pub id: String,
	pub is_locked: bool,
	pub book_club_book_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BookClubInvitation {
	pub id: String,
	pub role: i32,
	pub user_id: String,
	pub book_club_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BookClubMemberFavoriteBook {
	pub id: String,
	pub title: Option<String>,
	pub author: Option<String>,
	pub url: Option<String>,
	pub notes: Option<String>,
	pub member_id: String,
	pub book_id: Option<String>,
	pub image_url: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BookClubMember {
	pub id: String,
	pub display_name: Option<String>,
	pub is_creator: bool,
	pub hide_progress: bool,
	pub private_membership: bool,
	pub role: i32,
	pub user_id: String,
	pub book_club_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(book_club_id))]
pub struct BookClubSchedule {
	pub default_interval_days: Option<i32>,
	pub book_club_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct BookClub {
	pub id: String,
	pub name: String,
	pub description: Option<String>,
	pub is_private: bool,
	pub member_role_spec: Option<Vec<u8>>,
	pub created_at: NaiveDateTime,
	pub emoji: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Bookmark {
	pub id: String,
	pub preview_content: Option<String>,
	pub epubcfi: Option<String>,
	pub page: Option<i32>,
	pub media_id: String,
	pub user_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Collection {
	pub id: String,
	pub name: String,
	pub description: Option<String>,
	pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct EmailerSendRecord {
	pub id: i32,
	pub emailer_id: i32,
	pub recipient_email: String,
	pub attachment_meta: Option<Vec<u8>>,
	pub sent_at: NaiveDateTime,
	pub sent_by_user_id: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Emailer {
	pub id: i32,
	pub name: String,
	pub is_primary: bool,
	pub sender_email: String,
	pub sender_display_name: String,
	pub username: String,
	pub encrypted_password: String,
	pub smtp_host: String,
	pub smtp_port: i32,
	pub tls_enabled: bool,
	pub max_attachment_size_bytes: Option<i32>,
	pub max_num_attachments: Option<i32>,
	pub last_used_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct FinishedReadingSession {
	pub id: String,
	pub started_at: NaiveDateTime,
	pub completed_at: NaiveDateTime,
	pub media_id: String,
	pub user_id: String,
	pub device_id: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct JobScheduleConfig {
	pub id: String,
	pub interval_secs: i32,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Job {
	pub id: String,
	pub name: String,
	pub description: Option<String>,
	pub status: String,
	pub save_state: Option<Vec<u8>>,
	pub output_data: Option<Vec<u8>>,
	pub ms_elapsed: i64,
	pub created_at: NaiveDateTime,
	pub completed_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct LastLibraryVisit {
	pub rowid: i32,
	pub user_id: String,
	pub library_id: String,
	pub timestamp: NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Library {
	pub id: String,
	pub name: String,
	pub description: Option<String>,
	pub path: String,
	pub status: String,
	pub updated_at: NaiveDateTime,
	pub created_at: NaiveDateTime,
	pub emoji: Option<String>,
	pub config_id: String,
	pub job_schedule_config_id: Option<String>,
	pub last_scanned_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct LibraryConfig {
	pub id: String,
	pub convert_rar_to_zip: bool,
	pub hard_delete_conversions: bool,
	pub default_reading_dir: String,
	pub default_reading_mode: String,
	pub default_reading_image_scale_fit: String,
	pub generate_file_hashes: bool,
	pub generate_koreader_hashes: bool,
	pub process_metadata: bool,
	pub library_pattern: String,
	pub thumbnail_config: Option<Vec<u8>>,
	pub ignore_rules: Option<Vec<u8>>,
	pub library_id: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct LibraryScanRecord {
	pub id: i32,
	pub options: Option<Vec<u8>>,
	pub timestamp: NaiveDateTime,
	pub library_id: String,
	pub job_id: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Log {
	pub id: i32,
	pub level: String,
	pub message: String,
	pub timestamp: NaiveDateTime,
	pub job_id: Option<String>,
	pub context: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Media {
	pub id: String,
	pub name: String,
	pub size: i64,
	pub extension: String,
	pub pages: i32,
	pub updated_at: NaiveDateTime,
	pub created_at: NaiveDateTime,
	pub modified_at: Option<NaiveDateTime>,
	pub hash: Option<String>,
	pub path: String,
	pub status: String,
	pub series_id: Option<String>,
	pub deleted_at: Option<NaiveDateTime>,
	pub koreader_hash: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct MediaAnnotation {
	pub id: String,
	pub highlighted_text: Option<String>,
	pub epubcfi: Option<String>,
	pub page: Option<i32>,
	pub page_coordinates_x: Option<f32>,
	pub page_coordinates_y: Option<f32>,
	pub notes: Option<String>,
	pub user_id: String,
	pub media_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct MediaMetadata {
	pub id: String,
	pub title: Option<String>,
	pub series: Option<String>,
	pub number: Option<f32>,
	pub volume: Option<i32>,
	pub summary: Option<String>,
	pub notes: Option<String>,
	pub genre: Option<String>,
	pub year: Option<i32>,
	pub month: Option<i32>,
	pub day: Option<i32>,
	pub writers: Option<String>,
	pub pencillers: Option<String>,
	pub inkers: Option<String>,
	pub colorists: Option<String>,
	pub letterers: Option<String>,
	pub cover_artists: Option<String>,
	pub editors: Option<String>,
	pub publisher: Option<String>,
	pub links: Option<String>,
	pub characters: Option<String>,
	pub teams: Option<String>,
	pub page_count: Option<i32>,
	pub media_id: Option<String>,
	pub age_rating: Option<i32>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Notifier {
	pub id: i32,
	pub type_: String,
	pub config: Vec<u8>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct PageDimension {
	pub id: String,
	pub dimensions: String,
	pub metadata_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct ReadingListItem {
	pub rowid: i32,
	pub display_order: i32,
	pub media_id: String,
	pub reading_list_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct ReadingListRule {
	pub rowid: i32,
	pub role: i32,
	pub user_id: String,
	pub reading_list_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct ReadingList {
	pub id: String,
	pub name: String,
	pub description: Option<String>,
	pub updated_at: NaiveDateTime,
	pub visibility: String,
	pub ordering: String,
	pub creating_user_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct ReadingSession {
	pub id: String,
	pub page: Option<i32>,
	pub percentage_completed: Option<f32>,
	pub epubcfi: Option<String>,
	pub koreader_progress: Option<String>,
	pub started_at: NaiveDateTime,
	pub updated_at: NaiveDateTime,
	pub media_id: String,
	pub user_id: String,
	pub device_id: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct RegisteredEmailDevice {
	pub id: i32,
	pub name: String,
	pub email: String,
	pub forbidden: bool,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct RegisteredReadingDevice {
	pub id: String,
	pub name: String,
	pub kind: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Review {
	pub id: String,
	pub rating: i32,
	pub content: Option<String>,
	pub is_private: bool,
	pub media_id: String,
	pub user_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Series {
	pub id: String,
	pub name: String,
	pub description: Option<String>,
	pub updated_at: NaiveDateTime,
	pub created_at: NaiveDateTime,
	pub path: String,
	pub status: String,
	pub library_id: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(series_id))]
pub struct SeriesMetadata {
	pub meta_type: String,
	pub title: Option<String>,
	pub summary: Option<String>,
	pub publisher: Option<String>,
	pub imprint: Option<String>,
	pub comicid: Option<i32>,
	pub volume: Option<i32>,
	pub booktype: Option<String>,
	pub age_rating: Option<i32>,
	pub status: Option<String>,
	pub series_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct ServerConfig {
	pub id: String,
	pub public_url: Option<String>,
	pub initial_wal_setup_complete: bool,
	pub job_schedule_config_id: Option<String>,
	pub encryption_key: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct ServerInvitation {
	pub id: String,
	pub secret: String,
	pub email: Option<String>,
	pub granted_permissions: Option<String>,
	pub created_at: NaiveDateTime,
	pub expires_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Session {
	pub id: String,
	pub created_at: NaiveDateTime,
	pub expiry_time: NaiveDateTime,
	pub data: Vec<u8>,
	pub user_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct SmartListAccessRule {
	pub rowid: i32,
	pub role: i32,
	pub user_id: String,
	pub smart_list_id: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(rowid))]
pub struct SmartListView {
	pub rowid: i32,
	pub name: String,
	pub list_id: String,
	pub data: Vec<u8>,
}

#[derive(Queryable, Debug)]
pub struct SmartList {
	pub id: String,
	pub name: String,
	pub description: Option<String>,
	pub filters: Vec<u8>,
	pub joiner: String,
	pub default_grouping: String,
	pub visibility: String,
	pub creator_id: String,
}

#[derive(Queryable, Debug)]
pub struct Tag {
	pub id: String,
	pub name: String,
}

#[derive(Queryable, Debug)]
pub struct UserLoginActivity {
	pub id: String,
	pub ip_address: String,
	pub user_agent: String,
	pub authentication_successful: bool,
	pub timestamp: NaiveDateTime,
	pub user_id: String,
}

#[derive(Queryable, Debug)]
pub struct UserPreference {
	pub id: String,
	pub preferred_layout_mode: String,
	pub locale: String,
	pub app_theme: String,
	pub app_font: String,
	pub primary_navigation_mode: String,
	pub layout_max_width_px: Option<i32>,
	pub show_query_indicator: bool,
	pub enable_live_refetch: bool,
	pub enable_discord_presence: bool,
	pub enable_compact_display: bool,
	pub enable_gradients: bool,
	pub enable_double_sidebar: bool,
	pub enable_replace_primary_sidebar: bool,
	pub enable_hide_scrollbar: bool,
	pub prefer_accent_color: bool,
	pub show_thumbnails_in_headers: bool,
	pub enable_job_overlay: bool,
	pub navigation_arrangement: Option<Vec<u8>>,
	pub home_arrangement: Option<Vec<u8>>,
	pub user_id: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct User {
	pub id: String,
	pub username: String,
	pub hashed_password: String,
	pub is_server_owner: bool,
	pub avatar_url: Option<String>,
	pub last_login: Option<NaiveDateTime>,
	pub created_at: NaiveDateTime,
	pub deleted_at: Option<NaiveDateTime>,
	pub is_locked: bool,
	pub max_sessions_allowed: Option<i32>,
	pub permissions: Option<String>,
	pub user_preferences_id: Option<String>,
}
