name: 'Compile Web Application'
description: 'Compile stump web'

runs:
  using: composite
  steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: yarn install
      working-directory: apps/web

    - name: Build app
      shell: bash
      run: yarn build
      working-directory: apps/web

    - name: Upload bundle
      uses: ./.github/actions/upload-artifact
      with:
        upload-name: webapp
        upload-path: apps/web/dist
