name: Compile Web Application
description: Compile stump web

inputs:
  app:
    description: 'The app to build, i.e. web, desktop'
    default: 'web'

runs:
  using: composite
  steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Setup Node and Yarn
      uses: ./.github/actions/setup-yarn

    - name: Build app
      shell: bash
      run: yarn exec vite build
      working-directory: apps/${{ inputs.app }}

    - name: Upload bundle
      uses: ./.github/actions/upload-artifact
      with:
        upload-name: webapp
        upload-path: apps/${{ inputs.app }}/dist
