[package]
name = "order-by-gen"
edition = "2021"
version.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true
doctest = false

[dependencies]
paste = "1.0.15"
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
