name: 'Setup system dependencies'
description: 'Install system dependencies and setup cache'

runs:
  using: 'composite'
  steps:
    - name: Configure environment
      run: |
        if [[ ${{ runner.name }} == 'manjaro-az' || ${{ runner.os }} == 'Windows' ]]; then
          echo "RUN_SETUP=false" >> $GITHUB_ENV
        else
          echo "RUN_SETUP=true" >> $GITHUB_ENV
        fi
      shell: bash

    - name: System setup
      if: ${{ env.RUN_SETUP == 'true' }}
      shell: bash
      run: CHECK_NODE=0 CHECK_CARGO=0 DEV_SETUP=0 ./scripts/system-setup.sh

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
