name: 'Setup system dependencies'
description: 'Install system dependencies and setup cache'

runs:
  using: 'composite'
  steps:
    - name: System setup
      # TODO: determine if this is actually OK... I keep getting locked out of sudo
      # because the setup script has a few sudo commands that fail. I either need to setup
      # some sort of askpass or (ideally) not run setup if it isn't needed on the self-hosted runner...
      # Only run if we're NOT on a self-hosted runner. This check is really naive and should
      # be changed. I doubt I'll host more than one runner, so this is fine for now.
      if: runner.name != 'manjaro-az'
      shell: bash
      run: CHECK_NODE=0 CHECK_CARGO=0 DEV_SETUP=0 ./scripts/system-setup.sh

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
