# https://moonrepo.dev/docs/config/global-project
$schema: 'https://moonrepo.dev/schemas/global-project.json'

fileGroups:
  app: []
  configs:
    - '*.{js,json,yml,yaml}'
  sources:
    - 'public/**/*'
    - 'src/**/*'
    - 'types/**/*'
  tests:
    - 'tests/**/*.test.*'
    - '**/__tests__/**/*'
  assets:
    - 'assets/**/*'
    - 'images/**/*'
    - 'static/**/*'
    - '**/*.{scss,css}'
    - '**/*.{md,mdx}'

#! FIXME: for some god forsaken reason, I cannot for the life of me get the moon
#! prettier run to align with the config file... The biggest annoyance is for .json
#! files, it seems to not use hard tabs. Drives me wild.
#* https://moonrepo.dev/docs/guides/examples/prettier

tasks:
  format:
    command:
      - 'prettier'
      - '--config'
      - '@in(4)'
      - '--ignore-path'
      - '@in(3)'
      - '--write'
      - '.'
    inputs:
      - 'src/**/*'
      - 'tests/**/*'
      - '**/*.{md,mdx,yml,yaml,json}'
      - '/.prettierignore'
      - '/prettier.config.js'

  format-check:
    command:
      - 'prettier'
      - '--config'
      - '@in(4)'
      - '--ignore-path'
      - '@in(3)'
      - '--check'
      - '.'
    inputs:
      - 'src/**/*'
      - 'tests/**/*'
      - '**/*.{md,mdx,yml,yaml,json}'
      - '/.prettierignore'
      - '/prettier.config.js'

  lint:
    command:
      - 'eslint'
      - '--ext'
      - '.ts,.tsx,.cts,.mts,.js,.jsx,.cjs,.mjs'
      - '--report-unused-disable-directives'
      - '--no-error-on-unmatched-pattern'
      - '--exit-on-fatal-error'
      - '--ignore-path'
      - '@in(2)'
      - '.'
    inputs:
      - '*.config.*'
      - '**/.eslintrc.*'
      - '/.eslintignore'
      - '/.eslintrc.*'
      - 'tsconfig.json'
      - '/tsconfig.eslint.json'
      - '/tsconfig.options.json'
      - '@group(app)'
      - '@globs(sources)'
      - '@globs(tests)'

  typecheck:
    command:
      - 'tsc'
      - '--build'
      - '--verbose'
    inputs:
      - '@group(app)'
      - '@globs(sources)'
      - '@globs(tests)'
      - 'tsconfig.json'
      - 'tsconfig.*.json'
      - '/tsconfig.options.json'
