#!/usr/bin/env bash

log_error() {
    echo $1 1>&2
    exit 1
}

# prisma uses some `include_str!` macros that are mapped to locations on the host machine. so
# when we build in docker, we need to correct these paths according to the docker workdir. 
# it's a bit of a hack, but it works lol
prisma_sed_correction() {
    set -ex; \
        # Match windows paths
        sed -i 's|[A-Z]:\\\\.*\\\\core\\\\prisma\\\\schema\.prisma|\/app\/core\/prisma\/schema.prisma|g' core/src/prisma.rs; \
        sed -i 's|[A-Z]:\\\\.*\\\\core\\\\prisma\\\\migrations|\/app\/core\/prisma\/migrations|g' core/src/prisma.rs; \
        # Match Unix paths
        sed -i 's|\/.*\/core\/prisma\/schema\.prisma|\/app\/core\/prisma\/schema.prisma|g' core/src/prisma.rs; \
        sed -i 's|\/.*\/core\/prisma\/migrations|\/app\/core\/prisma\/migrations|g' core/src/prisma.rs
}

workspaces_sed_correction() {
    set -ex; \
        sed -i '/core\/integration-tests/d' Cargo.toml; \
        sed -i '/apps\/desktop\/src-tauri/d' Cargo.toml; \
        sed -i '/crates\/prisma-cli/d' Cargo.toml
}

# Change all versions in package.json files AND Cargo.toml files to 'nightly'
nightly_sed_correction() {
    set -ex; \
        sed -i 's|version = ".*"|version = "nightly"|g' Cargo.toml; \
        sed -i 's|"version": ".*"|"version": "nightly"|g' package.json
}

# Change all versions in package.json files AND Cargo.toml files to 'experimental'
experimental_sed_correction() {
    set -ex; \
        sed -i 's|version = ".*"|version = "experimental"|g' Cargo.toml; \
        sed -i 's|"version": ".*"|"version": "experimental"|g' package.json
}

download_pdfium() {
    local arch=$1
    if [ "$arch" = "amd64" ]; then
        curl -sLo pdfium.tgz https://github.com/bblanchon/pdfium-binaries/releases/chromium/6002/pdfium-linux-x86.tgz
    elif [ "$arch" = "arm64" ]; then
        curl -sLo pdfium.tgz https://github.com/bblanchon/pdfium-binaries/releases/download/chromium/6002/pdfium-linux-arm64.tgz
    fi
    tar -xzvf pdfium.tgz -C /pdfium
    rm pdfium.tgz
}