name: 'Build Stump desktop app'
description: 'Compile the Stump desktop app'

inputs:
  platform:
    description: 'The plaform of the runner'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Setup Node and Yarn
      uses: ./.github/actions/setup-yarn

    - name: Setup rust
      uses: ./.github/actions/setup-rust

    # This action can be called to build in a Linux, macOS, or Windows runner
    # Linux
    - name: Compile server (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: yarn desktop build:linux
    # macOS (ARM)
    - name: Compile server (macOS)
      if: runner.os == 'macOS' && runner.arch == 'ARM64'
      shell: bash
      run: yarn desktop build:mac-arm
    # macOS (Intel)
    - name: Compile server (macOS Intel)
      if: runner.os == 'macOS' && runner.arch == 'X86'
      shell: bash
      run: yarn desktop build:mac-x64
    # Windows
    - name: Compile server (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: yarn desktop build:win
