-- CREATE TABLE IF NOT EXISTS `media` (
--   `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
--   `library_id` integer NOT NULL,
--   `name` text NOT NULL,
--   `description` text,
--   `year` integer,
--   `added_at` text,
--   `location` text NOT NULL,
--   FOREIGN KEY (`library_id`) REFERENCES `library` (`id`)
-- );

-- CREATE TABLE IF NOT EXISTS `library` (
--   `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
--   `name` text NOT NULL,
--   `directory` text NOT NULL,
--   `media_type` text NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS `users` (
--   `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
--   `username` text NOT NULL,
--   `password` text NOT NULL,
--   `role` text(5) NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS `preferences` (
--   `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
--   `user_id` integer NOT NULL,
--   `theme` text NOT NULL,
--   FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
-- );