name: Docker Release CI

# This workflow triggers when a PR is merged into `main`, but jobs have conditions to only run when:
# - A PR is closed, merged into `main`, from a branch that matches the pattern `release/v*.*.*`

on:
  pull_request:
    branches:
      - main
    types: [opened, closed, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  parse-semver:
    if: contains(github.event.pull_request.head.ref, 'release/v')
    name: Parse semver version
    runs-on: [ubuntu-22.04]
    outputs:
      version: ${{ steps.tag.outputs.version }}
      tags: ${{ steps.docker-tags.outputs.tags }}
    steps:
      - name: Extract version from branch name
        id: tag
        run: echo "version=$(echo ${{ github.event.pull_request.head.ref }} | sed -e 's/release\/v//')" >> $GITHUB_OUTPUT

      - name: Print the tag
        run: echo "The output version is ${{ steps.tag.outputs.version }}"

      - name: Configure docker tags
        id: docker-tags
        run: |
          echo "tags=latest,nightly,${{ steps.tag.outputs.version }}" >> $GITHUB_OUTPUT
          echo "Docker tags are latest, nightly, and ${{ steps.tag.outputs.version }}"

  push-or-load:
    if: contains(github.event.pull_request.head.ref, 'release/v')
    name: Configure docker load/push
    runs-on: [ubuntu-22.04]
    outputs:
      load: ${{ steps.configure.outputs.load }}
      push: ${{ steps.configure.outputs.push }}
      archs: ${{ steps.configure.outputs.archs }}
    steps:
      - name: Configure environment
        id: configure
        run: |
          if [[ ${{ github.event.pull_request.merged }} == true ]]; then
            echo "push=true" >> $GITHUB_OUTPUT
            echo "load=false" >> $GITHUB_OUTPUT
            echo "archs=arm64,amd64" >> $GITHUB_OUTPUT
          else
            echo "push=false" >> $GITHUB_OUTPUT
            echo "load=true" >> $GITHUB_OUTPUT
            echo "archs=amd64" >> $GITHUB_OUTPUT
          fi

      - name: Print the configuration
        run: |
          echo "Archs: ${{ steps.configure.outputs.archs }}"
          echo "Load: ${{ steps.configure.outputs.load }}"
          echo "Push: ${{ steps.configure.outputs.push }}"

  build-stable-docker:
    if: contains(github.event.pull_request.head.ref, 'release/v')
    name: Build docker image
    runs-on: [self-hosted-large]
    needs: [parse-semver, push-or-load]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push docker image
        uses: ./.github/actions/build-docker
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          tags: ${{ needs.parse-semver.outputs.tags }}
          load: ${{ needs.push-or-load.outputs.load }}
          push: ${{ needs.push-or-load.outputs.push }}
          archs: ${{ needs.push-or-load.outputs.archs }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
