name: 'Stump Unstable CI'

on:
  pull_request:
    branches:
      - unstable
  push:
    branches:
      - unstable
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build against'
        required: true
        default: 'unstable'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-changes-check:
    runs-on: [ubuntu-22.04]
    outputs:
      changes: ${{steps.filter.outputs.changes}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        if: github.event_name != 'workflow_dispatch'
        with:
          base: 'unstable'
          filters: |
            apps: ./apps/**
            core: ./core/**
            crates: ./crates/**
            docker: ./docker/**
            packages: ./packages/**
            workflow:
              - './.github/workflows/unstable.yml'
              - './.github/actions/**'

  unstable-docker-build:
    needs: code-changes-check
    name: Build docker image
    runs-on: [self-hosted]
    if: ${{ needs.code-changes-check.outputs.changes != '[]' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Setup and build docker image
        uses: ./.github/actions/build-docker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'unstable'
          build-channel: 'unstable'
          load: ${{ github.event_name == 'pull_request' }}
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          archs: 'amd64'
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
